/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-04-24 08:04:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>login</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<script src=\"http://lab.alexcican.com/set_cookies/cookie.js\"\r\n");
      out.write("\ttype=\"text/javascript\"></script>\r\n");
      out.write("<style>\r\n");
      out.write(".sort {\r\n");
      out.write("\tfont-size: 11px;\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: space-between;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sort a:hover {\r\n");
      out.write("\topacity: 0.3\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sort1 {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sort1 span {\r\n");
      out.write("\tmargin-left: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("a {\r\n");
      out.write("\tmargin-left: 0;\r\n");
      out.write("\tfont-size: 11px;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tfont-size: 11px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#_btnLogin:hover {\r\n");
      out.write("\topacity: 0.3\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#chk_save_id {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<form id=\"frm\">\r\n");
      out.write("\t\t<svg id=\"ryan\" viewBox=\"0 0 120 120\"\r\n");
      out.write("\t\t\txmlns=\"http://www.w3.org/2000/svg\">\r\n");
      out.write("            <path d=\"M0,150 C0,65 120,65 120,150\" fill=\"#e0a243\"\r\n");
      out.write("\t\t\t\tstroke=\"#000\" stroke-width=\"2.5\" />\r\n");
      out.write("            <g class=\"ears\">\r\n");
      out.write("                <path d=\"M46,32 L46,30 C46,16 26,16 26,30 L26,32\"\r\n");
      out.write("\t\t\t\tfill=\"#e0a243\" stroke=\"#000\" stroke-width=\"2.5\"\r\n");
      out.write("\t\t\t\tstroke-linecap=\"round\" transform=\"rotate(-10,38,24)\" />\r\n");
      out.write("                <path d=\"M74,32 L74,30 C74,16 94,16 94,30 L94,32\"\r\n");
      out.write("\t\t\t\tfill=\"#e0a243\" stroke=\"#000\" stroke-width=\"2.5\"\r\n");
      out.write("\t\t\t\tstroke-linecap=\"round\" transform=\"rotate(10,82,24)\" />\r\n");
      out.write("            </g>\r\n");
      out.write("            <circle cx=\"60\" cy=\"60\" r=\"40\" fill=\"#e0a243\" stroke=\"#000\"\r\n");
      out.write("\t\t\t\tstroke-width=\"2.5\" />\r\n");
      out.write("            <g class=\"eyes\">\r\n");
      out.write("                <!-- left eye and eyebrow-->\r\n");
      out.write("                <line x1=\"37\" x2=\"50\" y1=\"46\" y2=\"46\" stroke=\"#000\"\r\n");
      out.write("\t\t\t\tstroke-width=\"3\" stroke-linecap=\"round\" />\r\n");
      out.write("                <circle cx=\"44\" cy=\"55\" r=\"3\" fill=\"#000\" />\r\n");
      out.write("                <!-- right eye and eyebrow -->\r\n");
      out.write("                <line x1=\"70\" x2=\"83\" y1=\"46\" y2=\"46\" stroke=\"#000\"\r\n");
      out.write("\t\t\t\tstroke-width=\"3\" stroke-linecap=\"round\" />\r\n");
      out.write("                <circle cx=\"76\" cy=\"55\" r=\"3\" fill=\"#000\" />\r\n");
      out.write("            </g>\r\n");
      out.write("            <g class=\"muzzle\">\r\n");
      out.write("                <path\r\n");
      out.write("\t\t\t\td=\"M60,66 C58.5,61 49,63 49,69 C49,75 58,77 60,71 M60,66 C61.5,61 71,63 71,69 C71,75 62,77 60,71\"\r\n");
      out.write("\t\t\t\tfill=\"#fff\" />\r\n");
      out.write("                <path\r\n");
      out.write("\t\t\t\td=\"M60,66 C58.5,61 49,63 49,69 C49,75 58,77 60,71 M60,66 C61.5,61 71,63 71,69 C71,75 62,77 60,71\"\r\n");
      out.write("\t\t\t\tfill=\"#fff\" stroke=\"#000\" stroke-width=\"2.5\" stroke-linejoin=\"round\"\r\n");
      out.write("\t\t\t\tstroke-linecap=\"round\" />\r\n");
      out.write("                <polygon points=\"59,63.5,60,63.4,61,63.5,60,65\"\r\n");
      out.write("\t\t\t\tfill=\"#000\" stroke=\"#000\" stroke-width=\"5\" stroke-linejoin=\"round\" />\r\n");
      out.write("            </g>\r\n");
      out.write("            <path\r\n");
      out.write("\t\t\t\td=\"M40,105 C10,140 110,140 80,105 L80,105 L70,111 L60,105 L50,111 L40,105\"\r\n");
      out.write("\t\t\t\tfill=\"#fff\" />\r\n");
      out.write("        </svg>\r\n");
      out.write("        <input type=\"hidden\" name=\"type\" value=\"loginStart\"> \r\n");
      out.write("\t\t<input name=\"id\" id=\"id\" type=\"text\" placeholder=\"ID(이메일형식)\"> <input\r\n");
      out.write("\t\t\tname=\"password\" id=\"password\" type=\"password\" placeholder=\"비밀번호\t\"> <input\r\n");
      out.write("\t\t\ttype=\"button\" id=\"_btnLogin\" value=\"Login\">\r\n");
      out.write("\t\t<div class=\"sort\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 회원가입 버튼 클릭시 regiButton() 호출 -->\r\n");
      out.write("\t\t\t<button type=\"button\" onclick=\"regiButton()\">회원가입</button>\r\n");
      out.write("\t\t\t<div class=\"sort1\">\r\n");
      out.write("\t\t\t\t<input type=\"checkbox\" id=\"chk_save_id\"> <span>아이디 저장</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\r\n");
      out.write("\t/* RegiInfoServlet으로 이동 */\r\n");
      out.write("\tfunction regiButton(){\r\n");
      out.write("\t\tlocation.href=\"register?type=moveRegister\"\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t// 로그인 버튼 클릭시에 동작하는 함수 \r\n");
      out.write("\t$(\"#_btnLogin\").click(function() {\r\n");
      out.write("\t\t\t\tif ($(\"#id\").val().trim() == \"\") {\r\n");
      out.write("\t\t\t\t\talert(\"id를 입력해 주십시오\");\r\n");
      out.write("\t\t\t\t\t$(\"#id\").focus();\r\n");
      out.write("\t\t\t\t} else if ($(\"#password\").val().trim() == \"\") {\r\n");
      out.write("\t\t\t\t\talert(\"password를 입력해 주십시오\");\r\n");
      out.write("\t\t\t\t\t$(\"#password\").focus();\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t//LoginServlet 으로 이동\r\n");
      out.write("\t\t\t\t\t$(\"#frm\").attr({\r\n");
      out.write("\t\t\t\t\t\t\"action\" : \"login\",\r\n");
      out.write("\t                    \"method\": \"post\"\r\n");
      out.write("\t\t\t\t\t}).submit();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar user_id = $.cookie(\"user_id\");\r\n");
      out.write("\t\t\tif (user_id != null) { // 지정한 쿠키가 있을 때\r\n");
      out.write("\t\t\t\t// alert(\"쿠키 있음\");\r\n");
      out.write("\t\t\t\t$(\"#id\").val(user_id);\r\n");
      out.write("\t\t\t\t$(\"#chk_save_id\").attr(\"checked\", \"checked\");\r\n");
      out.write("\t        }\r\n");
      out.write("\t        \r\n");
      out.write("\t\t\t$(\"#chk_save_id\").click(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif ($(\"#chk_save_id\").is(\":checked\")) { // 체크 되었을 때\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\tif ($(\"#id\").val().trim() == \"\") {\r\n");
      out.write("\t\t\t\t\t\talert(\"id를 입력해 주십시오\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#chk_save_id\").prop(\"checked\", false);\r\n");
      out.write("\t\t\t\t\t} else { // 정상 기입한 경우\r\n");
      out.write("\t\t\t\t\t\t// 쿠키 저장\r\n");
      out.write("\t\t\t\t\t\t$.cookie(\"user_id\", $(\"#id\").val().trim(), {\r\n");
      out.write("\t\t\t\t\t\t\texpires : 7,\r\n");
      out.write("\t\t\t\t\t\t\tpath : './'\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t//\talert(\"체크 없어짐\");\r\n");
      out.write("\t\t\t\t\t$.removeCookie(\"user_id\", {\r\n");
      out.write("\t\t\t\t\t\tpath : './'\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"script.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
