/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-04-24 08:04:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import main.BabyMemberDto;
import main.BabyMemberDto;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/./include/footer.jsp", Long.valueOf(1587715415236L));
    _jspx_dependants.put("/./include/header.jsp", Long.valueOf(1587715415244L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("main.BabyMemberDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Oh My Baby</title>\r\n");
      out.write("\r\n");
      out.write("<!-- favicon 16, 24, 32, 64, 152 -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"./images/front/favicon.ico\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" href=\"./images/front/icon_57.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"72x72\"\r\n");
      out.write("\thref=\"./images/front/icon_72.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"114x114\"\r\n");
      out.write("\thref=\"./images/front/icon_114.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"144x144\"\r\n");
      out.write("\thref=\"./images/front/icon_144.png\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"./css/front/reset.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/front/common.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/front/layout.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/front/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/front/jquery-3.1.0.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"js/front/jquery.bxslider.js\"></script>\r\n");
      out.write("<script src=\"js/front/common.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\">\r\n");
      out.write("<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 자바스크립트 -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");

	BabyMemberDto babyMemberDto = (BabyMemberDto) session.getAttribute("login");
	if (babyMemberDto != null) {
		System.out.println("로그인후 dto" + babyMemberDto.toString());
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<header class=\"headerWrap\">\r\n");
      out.write("\t\t<div class=\"header clearfix tr\">\r\n");
      out.write("\t\t\t<div class=\"header_topSec clearfix\">\r\n");
      out.write("\t\t\t\t");

					if (babyMemberDto != null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t");

					if (babyMemberDto.getAuth() == 1) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t<li>");
      out.print(babyMemberDto.getName());
      out.write("님 환영합니다</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"admin?type=moveAdmin\" id=\"loginBtn\">관리자페이지</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"login?type=logout\" id=\"loginBtn\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t<li>");
      out.print(babyMemberDto.getName());
      out.write("님 환영합니다</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"mypage_point.jsp\" id=\"loginBtn\">마이페이지</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"login?type=logout\" id=\"loginBtn\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"login?type=moveLogin\" id=\"loginBtn\">로그인</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"register?type=moveRegister\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"inner_header clearfix\">\r\n");
      out.write("\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t<a href=\"main.jsp\" class=\"logo\"> <img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"images/front/logo.png\"> <!-- <span>내 아이를 부탁해</span> -->\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t");

					if (babyMemberDto != null) {
						if (babyMemberDto.getAuth() == 1) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"gnb clearfix\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"mypage_point.jsp\">회원정보관리</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li><a href=\"\">회원정보 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\"></a></li> -->\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">Mypage</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_main.jsp\">예약내역 확인</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_imageUpdate.jsp\">프로필 사진 업데이트</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_point.jsp\">내 포인트 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_profile.jsp\">내 계정 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"employee.jsp\">Service</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"employee.jsp\">돌봄 신청</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"searchSitterBoard\">구인구직</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"comHere.jsp\">오시는길</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"qna.jsp\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- <li><a href=\"\">커뮤니티</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">후기게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">자유게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");
	}else {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul class=\"gnb clearfix\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"mypage_point.jsp\">Mypage</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_main.jsp\">예약내역 확인</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"mypage_imageUpdate.jsp\">프로필 사진 업데이트</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_point.jsp\">내 포인트 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_profile.jsp\">내 계정 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"employee.jsp\">Service</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"employee.jsp\">돌봄 신청</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"searchSitterBoard\">구인구직</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"comHere.jsp\">오시는길</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"qna.jsp\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- <li><a href=\"\">커뮤니티</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">후기게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">자유게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					}
					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"gnb clearfix\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"employee.jsp\">Service</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"employee.jsp\">돌봄 신청</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"searchSitterBoard\">구인구직</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"comHere.jsp\">오시는길</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"qna.jsp\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- <li><a href=\"\">커뮤니티</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">후기게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">자유게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					}
					
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!--// header -->");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("@import url(\"//unpkg.com/element-ui@2.13.0/lib/theme-chalk/index.css\");\r\n");
      out.write("\r\n");
      out.write(".el-carousel__item h3 {\r\n");
      out.write("\tcolor: #475669;\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\topacity: 0.75;\r\n");
      out.write("\tline-height: 200px;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".el-carousel__item:nth-child(2n) {\r\n");
      out.write("\tbackground-color: #99a9bf;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".el-carousel__item:nth-child(2n+1) {\r\n");
      out.write("\tbackground-color: #d3dce6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".el-carousel__container {\r\n");
      out.write("\theight: 400px !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text {\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".item {\r\n");
      out.write("\tmargin-bottom: 18px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".clearfix:before, .clearfix:after {\r\n");
      out.write("\tdisplay: table;\r\n");
      out.write("\tcontent: \"\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".clearfix:after {\r\n");
      out.write("\tclear: both\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-card {\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\tmargin-left: 20px;\r\n");
      out.write("\tmargin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-card-wrapper {\r\n");
      out.write("\tmargin-top: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-card-wrapper:last-of-type {\r\n");
      out.write("\tmargin-bottom: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".box-container {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tjustify-content: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".baby-welcome {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tmargin-top: 60px;\r\n");
      out.write("\tpadding-bottom: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".baby-welcome-text {\r\n");
      out.write("\tmargin-left: 20px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<!-- content 영역 -->\r\n");

	// BabyMemberDto babyMemberDto = (BabyMemberDto)session.getAttribute("login");
	if (babyMemberDto != null) {
		System.out.println("로그인후 dto" + babyMemberDto.toString());
		if (babyMemberDto.getAuth() == 1) {

      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tlocation.href = \"admin?type=moveAdmin\";\r\n");
      out.write("</script>\r\n");

	}
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"//unpkg.com/vue/dist/vue.js\"></script>\r\n");
      out.write("<script src=\"//unpkg.com/element-ui@2.13.0/lib/index.js\"></script>\r\n");
      out.write("<div id=\"app\">\r\n");
      out.write("\t<div>\r\n");
      out.write("\t\t<template> <el-carousel :interval=\"4000\" type=\"card\"\r\n");
      out.write("\t\t\theight=\"200px\"> <el-carousel-item v-for=\"list in lists\"\r\n");
      out.write("\t\t\t:key=\"list.img\"> <!-- <h3 class=\"medium\">{{ item }}</h3> -->\r\n");
      out.write("\t\t<img style=\"width: 100%; height: auto;\" :src=\"list.img\"> </el-carousel-item> </el-carousel> </template>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<el-divider></el-divider>\r\n");
      out.write("\t<div class=\"baby-welcome\">\r\n");
      out.write("\t\t<img style=\"width: 50%; border-radius: 10px;\"\r\n");
      out.write("\t\t\tsrc=\"https://cdn.pixabay.com/photo/2017/09/03/09/16/baby-2709666_1280.jpg\">\r\n");
      out.write("\t\t<div class=\"baby-welcome-text\"\r\n");
      out.write("\t\t\tstyle=\"display: flex; flex-direction: column; justify-content: center\">\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span style=\"color: #82B7E7; font-size: 40px;\">방문해주셔서 감사합니다</span><br>\r\n");
      out.write("\t\t\t\t<span style=\"display: block; margin-top: 40px;\"> <span>우리\r\n");
      out.write("\t\t\t\t\t\tOh My baby는 2020년 업계 최초로 비트캠프 인증(BA)을 획득한 영유아 서비스 전문 브랜드입니다.<br>\r\n");
      out.write("\t\t\t\t</span> <span>국내 영유야 보육/탁아 서비스 시스템을 선도해서 대중화하였으며 높은 인지도와 고품질의 <br></span>\r\n");
      out.write("\t\t\t\t\t<span>영유아 관련 다양한 서비스를 제공하고 있습니다</span>\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<div style=\"text-align: center; margin-top: 40px;\">\r\n");
      out.write("\t\t\t\t<el-button style=\"width:200px; height:60px;\" type=\"info\">회사\r\n");
      out.write("\t\t\t\t소개 보기</el-button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<el-divider></el-divider>\r\n");
      out.write("\t<div class=\"box-container\">\r\n");
      out.write("\t\t<div style=\"width: 960px; display: flex; flex-wrap: wrap;\">\r\n");
      out.write("\t\t\t<div v-for=\"items in users\" :key=\"items.name\">\r\n");
      out.write("\t\t\t\t<el-card class=\"box-card\">\r\n");
      out.write("\t\t\t\t<div slot=\"header\" class=\"clearfix\" style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t<span>이용자 후기</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"text item\">{{ '성명: ' + items.name }}</div>\r\n");
      out.write("\t\t\t\t<div class=\"text item\">{{ '별점: ' + items.star  }}</div>\r\n");
      out.write("\t\t\t\t<div class=\"text item\">{{ '이용자 후기: ' + items.review }}</div>\r\n");
      out.write("\t\t\t\t</el-card>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- <div class=\"box-card-wrapper\"\r\n");
      out.write("\t\t\tstyle=\"display: flex; justify-content: center\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<el-card class=\"box-card\">\r\n");
      out.write("\t\t\t<div slot=\"header\" class=\"clearfix\">\r\n");
      out.write("\t\t\t\t<span>Card name</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div v-for=\"o in 4\" :key=\"o\" class=\"text item\">{{'List item ' +\r\n");
      out.write("\t\t\t\to }}</div>\r\n");
      out.write("\t\t\t</el-card>\r\n");
      out.write("\t\t\t<el-card class=\"box-card\">\r\n");
      out.write("\t\t\t<div slot=\"header\" class=\"clearfix\">\r\n");
      out.write("\t\t\t\t<span>Card name</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div v-for=\"o in 4\" :key=\"o\" class=\"text item\">{{'List item ' +\r\n");
      out.write("\t\t\t\to }}</div>\r\n");
      out.write("\t\t\t</el-card>\r\n");
      out.write("\t\t</div>\r\n");
      out.write(" -->\r\n");
      out.write("\r\n");
      out.write("\t<el-divider></el-divider>\r\n");
      out.write("\t<div>Oh My Baby 프로젝트 연대기</div>\r\n");
      out.write("\t<div style=\"margin-left: 40px;\" class=\"block\">\r\n");
      out.write("\t\t<el-timeline> <el-timeline-item\r\n");
      out.write("\t\t\tv-for=\"(activity, index) in activities\" :key=\"index\"\r\n");
      out.write("\t\t\t:icon=\"activity.icon\" :type=\"activity.type\" :color=\"activity.color\"\r\n");
      out.write("\t\t\t:size=\"activity.size\" :timestamp=\"activity.timestamp\">\r\n");
      out.write("\t\t{{activity.content}} </el-timeline-item> </el-timeline>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<!-- <div class=\"containerWrap main\">\r\n");
      out.write("\t<div class=\"container_inner\">\r\n");
      out.write("\t\t필요 없으면 div 삭제 (필요한거 남기고!) 배결색은 style만 삭제하면 되요~~!!\r\n");
      out.write("\t\t<div class=\"cont1 content clearfix\" style=\"background-color: #ccc;\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"cont2 content clearfix\" style=\"background-color: #eee;\"></div>\r\n");
      out.write("\t\t<div class=\"cont3 content clearfix\" style=\"background-color: #ccc;\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div> -->\r\n");
      out.write("<!--// container -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"footerWrap\">\r\n");
      out.write("\t\t<div class=\"footer clearfix\">\r\n");
      out.write("\t\t\t<!-- <img src=\"images/front/\" alt=\"\" class=\"footer__logo\"> -->\r\n");
      out.write("\t\t\t<!-- <p>오마이베이비</p> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<address class=\"footer__info\">\r\n");
      out.write("\t\t\t\t<p class=\"mb10\"></p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"footer__menu\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"inner_list clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>대표이사: </li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>사업자 등록번호: </li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>주소:서울특별시 </li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"inner_list clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#n\">통신판매업신고 : </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#n\" class=\"btn_policy\">이용약관</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#n\" class=\"btn_personal\">개인정보취급방침</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>E-mail : </li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"inner_list clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>TEL : </li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>FAX : </li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>COPYRIGHT Corporation. ALL RIGHTS RESERVED.</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</address>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<!-- // footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 로그인 팝업창 -->\r\n");
      out.write("\t<div class=\"lp_bg\"></div>\r\n");
      out.write("\t<div class=\"lp_box lp_box_s lp_login\">\r\n");
      out.write("\t\t<h3 class=\"lp_sbj font_square\"><a href=\"index.html\">\r\n");
      out.write("\t\t\t\t<p>로그인</p>\r\n");
      out.write("\t\t\t</a></h3>\r\n");
      out.write("\t\t<a href=\"#n\" class=\"btn_close_lp\"><img src=\"images/front/ico_close_lp_s.png\" alt=\"닫기\"></a>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"lp_cn tc\">\r\n");
      out.write("\t\t\t<input type=\"email\" class=\"user_email mb5\" placeholder=\"이메일\" style=\"width: 100%;\">\r\n");
      out.write("\t\t\t<input type=\"password\" class=\"user_pw\" placeholder=\"비밀번호\" style=\"width: 100%;\">\r\n");
      out.write("\t\t\t<p class=\"login_setting mb10 clearfix tl\">\r\n");
      out.write("\t\t\t\t<span class=\"pr10\"><input type=\"checkbox\"><label>ID 저장</label></span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"#n\" class=\"btn_gray_s fr pw_reset_info\">비밀번호 설정</a>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<a href=\"#n\" class=\"btn_blue_l btn_lp_login2\">로그인</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("/* new Vue().$mount('#app'); */\r\n");
      out.write("let app1 = new Vue({\r\n");
      out.write("\tel: \"#app\",\r\n");
      out.write("\tdata() {\r\n");
      out.write("\t\treturn{\r\n");
      out.write("\t\t\tlists:[{img: \"https://cdn.pixabay.com/photo/2013/02/21/19/10/mother-84628_1280.jpg\"},\r\n");
      out.write("\t\t\t{img: \"https://cdn.pixabay.com/photo/2012/03/04/01/01/baby-22194_1280.jpg\"},\t\r\n");
      out.write("\t\t\t\t{img: \"https://cdn.pixabay.com/photo/2018/03/28/04/59/child-3268265_1280.jpg\"}],\r\n");
      out.write("\t\t\t\t activities: [{\r\n");
      out.write("\t\t\t          content: 'Oh-my-baby 프로젝트 종료',\r\n");
      out.write("\t\t\t          timestamp: '2020-02-21 17:00',\r\n");
      out.write("\t\t\t          size: 'large',\r\n");
      out.write("\t\t\t          type: 'primary',\r\n");
      out.write("\t\t\t          icon: 'el-icon-more'\r\n");
      out.write("\t\t\t        }, {\r\n");
      out.write("\t\t\t          content: '프로젝트 진행중',\r\n");
      out.write("\t\t\t          timestamp: '2020-02-10 12:46',\r\n");
      out.write("\t\t\t          color: '#0bbd87'\r\n");
      out.write("\t\t\t        }, {\r\n");
      out.write("\t\t\t          content: 'Oh-My-Baby 탄생',\r\n");
      out.write("\t\t\t          timestamp: '2020-02-05 12:46',\r\n");
      out.write("\t\t\t          size: 'large',\r\n");
      out.write("\t\t\t          color: '#0bbd87'\r\n");
      out.write("\t\t\t        }, {\r\n");
      out.write("\t\t\t          content: '팀프로젝트 시작',\r\n");
      out.write("\t\t\t          timestamp: '2020-02-04 10:00',\r\n");
      out.write("\t\t\t          color: '#0bbd87'\r\n");
      out.write("\t\t\t        }],\r\n");
      out.write("\t\t\t         users:[{\r\n");
      out.write("\t\t\t        \tname: \"홍길동\",\r\n");
      out.write("\t\t\t        \tstar: \"⭐⭐⭐⭐⭐\",\r\n");
      out.write("\t\t\t        \treview: \"너무 친절하게 돌봐주세요\"\r\n");
      out.write("\t\t\t        },\r\n");
      out.write("\t\t\t        {\r\n");
      out.write("\t\t\t        \tname: \"일지매\",\r\n");
      out.write("\t\t\t        \tstar: \"⭐⭐⭐⭐⭐\",\r\n");
      out.write("\t\t\t        \treview: \"너무 친절\"\r\n");
      out.write("\t\t\t        },\r\n");
      out.write("\t\t\t        {\r\n");
      out.write("\t\t\t        \tname: \"정수동\",\r\n");
      out.write("\t\t\t        \tstar: \"⭐⭐⭐⭐⭐\",\r\n");
      out.write("\t\t\t        \treview: \"너무 친절하게 돌봐주세요\"\r\n");
      out.write("\t\t\t        }, \r\n");
      out.write("\t\t\t        {\r\n");
      out.write("\t\t\t        \tname: \"정보라\",\r\n");
      out.write("\t\t\t        \tstar: \"⭐⭐⭐⭐⭐\",\r\n");
      out.write("\t\t\t        \treview: \"너무 친절하게 돌봐주세요\"\r\n");
      out.write("\t\t\t        }, {\r\n");
      out.write("\t\t\t        \tname: \"이민제\",\r\n");
      out.write("\t\t\t        \tstar: \"⭐⭐⭐⭐⭐\",\r\n");
      out.write("\t\t\t        \treview: \"너무 친절하게 돌봐주세요\"\r\n");
      out.write("\t\t\t        }, {\r\n");
      out.write("\t\t\t        \tname: \"방경률\",\r\n");
      out.write("\t\t\t        \tstar: \"⭐⭐⭐⭐⭐\",\r\n");
      out.write("\t\t\t        \treview: \"너무 친절하게 돌봐주세요\"\r\n");
      out.write("\t\t\t        },       {\r\n");
      out.write("\t\t\t        \tname: \"황밝으리\",\r\n");
      out.write("\t\t\t        \tstar: \"⭐⭐⭐⭐⭐\",\r\n");
      out.write("\t\t\t        \treview: \"너무 친절하게 돌봐주세요\"\r\n");
      out.write("\t\t\t        }, \r\n");
      out.write("\t\t\t        {\r\n");
      out.write("\t\t\t        \tname: \"이온유\",\r\n");
      out.write("\t\t\t        \tstar: \"⭐⭐⭐⭐⭐\",\r\n");
      out.write("\t\t\t        \treview: \"너무 친절하게 돌봐주세요\"\r\n");
      out.write("\t\t\t        },\r\n");
      out.write("\t\t\t        {\r\n");
      out.write("\t\t\t        \tname: \"김아무개\",\r\n");
      out.write("\t\t\t        \tstar: \"⭐⭐⭐⭐⭐\",\r\n");
      out.write("\t\t\t        \treview: \"너무 친절하게 돌봐주세요\"\r\n");
      out.write("\t\t\t        }] \r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}); \r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
