/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-04-24 08:23:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import main.BabyMemberDao;
import main.BabyMemberDto;
import main.BabyMemberDto;

public final class mypage_005fprofile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/./include/footer.jsp", Long.valueOf(1587715415236L));
    _jspx_dependants.put("/./include/header.jsp", Long.valueOf(1587715415244L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("main.BabyMemberDao");
    _jspx_imports_classes.add("main.BabyMemberDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Oh My Baby</title>\r\n");
      out.write("\r\n");
      out.write("<!-- favicon 16, 24, 32, 64, 152 -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"./images/front/favicon.ico\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" href=\"./images/front/icon_57.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"72x72\"\r\n");
      out.write("\thref=\"./images/front/icon_72.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"114x114\"\r\n");
      out.write("\thref=\"./images/front/icon_114.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"144x144\"\r\n");
      out.write("\thref=\"./images/front/icon_144.png\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"./css/front/reset.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/front/common.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/front/layout.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/front/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/front/jquery-3.1.0.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"js/front/jquery.bxslider.js\"></script>\r\n");
      out.write("<script src=\"js/front/common.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\">\r\n");
      out.write("<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 자바스크립트 -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");

	BabyMemberDto babyMemberDto = (BabyMemberDto) session.getAttribute("login");
	if (babyMemberDto != null) {
		System.out.println("로그인후 dto" + babyMemberDto.toString());
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<header class=\"headerWrap\">\r\n");
      out.write("\t\t<div class=\"header clearfix tr\">\r\n");
      out.write("\t\t\t<div class=\"header_topSec clearfix\">\r\n");
      out.write("\t\t\t\t");

					if (babyMemberDto != null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t");

					if (babyMemberDto.getAuth() == 1) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t<li>");
      out.print(babyMemberDto.getName());
      out.write("님 환영합니다</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"admin?type=moveAdmin\" id=\"loginBtn\">관리자페이지</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"login?type=logout\" id=\"loginBtn\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t<li>");
      out.print(babyMemberDto.getName());
      out.write("님 환영합니다</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"mypage_point.jsp\" id=\"loginBtn\">마이페이지</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"login?type=logout\" id=\"loginBtn\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"login?type=moveLogin\" id=\"loginBtn\">로그인</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"register?type=moveRegister\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"inner_header clearfix\">\r\n");
      out.write("\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t<a href=\"main.jsp\" class=\"logo\"> <img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"images/front/logo.png\"> <!-- <span>내 아이를 부탁해</span> -->\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t");

					if (babyMemberDto != null) {
						if (babyMemberDto.getAuth() == 1) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"gnb clearfix\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"mypage_point.jsp\">회원정보관리</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li><a href=\"\">회원정보 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\"></a></li> -->\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">Mypage</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_main.jsp\">예약내역 확인</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_imageUpdate.jsp\">프로필 사진 업데이트</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_point.jsp\">내 포인트 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_profile.jsp\">내 계정 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"employee.jsp\">Service</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"employee.jsp\">돌봄 신청</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"searchSitterBoard\">구인구직</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"comHere.jsp\">오시는길</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"qna.jsp\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- <li><a href=\"\">커뮤니티</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">후기게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">자유게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");
	}else {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul class=\"gnb clearfix\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"mypage_point.jsp\">Mypage</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_main.jsp\">예약내역 확인</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"mypage_imageUpdate.jsp\">프로필 사진 업데이트</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_point.jsp\">내 포인트 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_profile.jsp\">내 계정 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"employee.jsp\">Service</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"employee.jsp\">돌봄 신청</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"searchSitterBoard\">구인구직</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"comHere.jsp\">오시는길</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"qna.jsp\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- <li><a href=\"\">커뮤니티</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">후기게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">자유게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					}
					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"gnb clearfix\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"employee.jsp\">Service</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"employee.jsp\">돌봄 신청</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"searchSitterBoard\">구인구직</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"comHere.jsp\">오시는길</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"qna.jsp\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- <li><a href=\"\">커뮤니티</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">후기게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">자유게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					}
					
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!--// header -->");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".abs {\r\n");
      out.write("\tcolor: #ff9999\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypage .boxs {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-direction: row;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\r\n");
      out.write("\t/*     margin-right: 10px; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypage .box1 {\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("\theight: 620px;\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\t/*   align-self:center; */\r\n");
      out.write("\tbackground-color: rgba(205, 255, 254, 0.8);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypage .box2 {\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("\theight: 620px;\r\n");
      out.write("\twidth: 500px;\r\n");
      out.write("\tbackground-color: rgba(190, 255, 239, 0.8);\r\n");
      out.write("\t padding-left: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".mypage .box3 {\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("\theight: 620px;\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\tbackground-color: rgba(190, 255, 239, 0.8);\r\n");
      out.write("\tpadding-top: 60px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding-right:70px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write(".menu>a:hover {\r\n");
      out.write("text-decoration:underline;\r\n");
      out.write("color: #ff9999;\r\n");
      out.write("\r\n");
      out.write("}  \r\n");
      out.write(".mypage .content {\r\n");
      out.write("margin-bottom:100px;\r\n");
      out.write("}  \r\n");
      out.write("\r\n");
      out.write("#finalUpdateBtn{\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");

	BabyMemberDto dto = (BabyMemberDto) request.getSession().getAttribute("login");
    BabyMemberDao dao = BabyMemberDao.getInstance();
    
    


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- content 영역 -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"container_inner mypage\">\r\n");
      out.write("\t<!-- 필요 없으면 div 삭제 (필요한거 남기고!) 배결색은 style만 삭제하면 되요~~!! -->\r\n");
      out.write("\t<div class=\"cont1 content clearfix mypage\" style=\"height: 620px\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"boxs box1\">\r\n");
      out.write("\t\t\t<p style=\"padding-top: 30px;\">\r\n");
      out.write("\t\t\t\t<b class=\"abs\" style=\"font-size: 25pt;\">MyPage</b>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");
	if (dto.getRealFileName() == null || dto.getRealFileName() == "null") {
					
      out.write("\r\n");
      out.write("\t\t\t\t<span>\t<img src='./image/mainImage.png'\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border-radius: 100%;\" width='110x' height='110px'> </span>\r\n");
      out.write("\t\t\t\t\t");

						} else {
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<span>\t<img src='http://localhost:8097/ProjectBaby/upload/");
      out.print(dto.getRealFileName());
      out.write("'\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border-radius: 100%;\" width='110px' height='110px'> </span>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table style=\"background-color: #f0f0f0; height: 30px;\">\r\n");
      out.write("\t\t\t\t<col width=\"130px\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"text-align: center; font-size: 15pt;\">\r\n");
      out.write("\t\t\t\t\t\t<p style=\"padding-top: 5px;\">");
      out.print(dto.getName());
      out.write("님\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<p\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"font-size: 9pt; text-align: center; font-weight: bold; padding-bottom: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(dto.getId());
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<table\r\n");
      out.write("\t\t\t\t\tstyle=\"background-color: #f0f0f0; size: '30'; font-size: '14px'; height: '13px'; margin-left: 50px;\">\r\n");
      out.write("\t\t\t\t\t<col width=\"200px\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t<p style=\"margin: 3px; padding-top: 17px;\" class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"mypage_main.jsp\">예약 내역 확인</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t<p style=\"margin: 3px;\" class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"mypage_imageUpdate.jsp\">프로필 사진 업데이트</a>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t<p style=\"margin: 3px;\" class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"mypage_point.jsp\">내 포인트 관리</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <a href=\"bbsWrite?type=write\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t\t<p style=\"margin: 3px; color: #ff9999; padding-bottom: 17px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t&nbsp;&nbsp;<img src='./image/arrow.png' width='10px'\r\n");
      out.write("\t\t\t\t\t\t\t\t\theight='10px' /> &nbsp; <a href=\"mypage_profile.jsp\">내 계정\r\n");
      out.write("\t\t\t\t\t\t\t\t\t관리</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<form class=\"update_form\" id=\"update_form\" action=\"ProfileUpdateServlet\" method=\"get\">\r\n");
      out.write("\t\t\r\n");
      out.write("<!-- \t=================================    box2 시작   =================================   -->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"boxs box2\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<p style=\"padding-top: 50px;\">\r\n");
      out.write("\t\t\t\t\t<b class=\"title\" style=\"font-size: 15pt; color: #82a3d4;\">개인정보 수정</b>\r\n");
      out.write("\t\t\t\t</p><br>\r\n");
      out.write("\t\t\t\t<table class=\"box1_table\">\r\n");
      out.write("\t\t\t\t\t<col style=\"width: 120px;\">\r\n");
      out.write("\t\t\t\t\t<col style=\"width: 320px;\">\r\n");
      out.write("\t\t\t\t\t<tr  style=\" height: 35px;\">\r\n");
      out.write("\t\t\t\t\t\t<td>id :</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"text\" name=\"id\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 200px; height: 30px;\" value=\"");
      out.print(dto.getId());
      out.write("\" readonly=\"readonly\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr style=\" height: 35px;\">\r\n");
      out.write("\t\t\t\t\t\t<td>Password :</td>\r\n");
      out.write("\t\t\t\t\t\t<td><input type=\"password\" name=\"password\" id=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"패스워드를 입력해주세요\" style=\"width: 200px; height: 30px\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr style=\" height: 35px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<td>이름 : </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\" name=\"name\"\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 200px; height: 30px;\" value=\"");
      out.print(dto.getName() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t    <tr style=\" height: 35px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<td>핸드폰번호 : </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\tname=\"phoneNumber\" style=\"width: 200px; height: 30px;\" value=\"");
      out.print(dto.getPhoneNumber() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-address\">\r\n");
      out.write("\t\t\t\t\t<br>\t\r\n");
      out.write("\t\t\t\t\t\t<p>주소</p> \r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"zipCode\" id=\"sample4_postcode\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"우편번호\" style=\"width: 300px; height: 30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"button\" onclick=\"sample4_execDaumPostcode()\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"우편번호 찾기\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"roadAddress\" id=\"sample4_roadAddress\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"도로명주소\" size=\"20\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 300px; height: 30px;\"  value=\"");
      out.print(dto.getAddress() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<span id=\"guide\" style=\"color: #999; display: none\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" name=\"detailAddress\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tid=\"sample4_detailAddress\" placeholder=\"상세주소\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 300px; height: 30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\t\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t<!-- \t ============================= hidden/visable 부분   =============================\t\t -->\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t");

		if (dto.getAuth() == 3 || dto.getAuth() == 9) {        //일반회원의 경우
	
      out.write("\r\n");
      out.write("\t\t\t<div class=\"changeView\" Style=\"visibility: hidden;\">\t\t\r\n");
      out.write("\t");

		} else if (dto.getAuth() == 4 || dto.getAuth() == 5 || dto.getAuth() == 6 || dto.getAuth() == 8) { //시터의 경우
    
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t<div class=\"changeView\" >\t\t\r\n");
      out.write("    ");

		}else{
	
      out.write("\r\n");
      out.write("\t\t\t<div class=\"changeView\" >\t\r\n");
      out.write("\t");

		}
	
      out.write("\r\n");
      out.write("\t\t\t\t\t<table class=\"box1_table\">\r\n");
      out.write("\t\t\t\t\t<col style=\"width: 120px;\">\r\n");
      out.write("\t\t\t\t\t<col style=\"width: 320px;\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t <tr style=\" height: 35px;\">\r\n");
      out.write("\t\t\t<!-- \t<div class=\"hidden_visable\" style=\"visibility: hidden;\" > -->\r\n");
      out.write("\t\t\t\t\t\t\t<td>원하는 시급 : </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t <input type=\"number\" name=\"wantPay\" step = 100\r\n");
      out.write("\t\t\t\t\t\t\t\tmin=\"8600\"  style=\"width: 134px; height: 30px;\" value=\"");
      out.print(dto.getWantPay());
      out.write("\">원\r\n");
      out.write("\t\t\t\t\t\t    </td> \r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr style=\" height: 35px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<td>경력 : </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t <select id=\"career\" name=\"career\" >\t \r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"신입\">신입</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"1~3년\">1~3년</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"4~5년\">4~5년</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"5년초과\">5년초과</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t    </td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<!-- \t</div> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr style=\" height: 35px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<span>원하는 요일 : </span> \r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t<span><input name=\"wantDate\" id=\"wantDate\" type=\"checkbox\"  value=\"월\">월</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span><input name=\"wantDate\" id=\"wantDate\" type=\"checkbox\"  value=\"화\">화</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span><input name=\"wantDate\" id=\"wantDate\" type=\"checkbox\" value=\"수\">수</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span><input name=\"wantDate\" id=\"wantDate\" type=\"checkbox\" value=\"목\">목</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span> <input name=\"wantDate\" id=\"wantDate\" type=\"checkbox\" value=\"금\">금\r\n");
      out.write("\t\t\t\t\t\t\t</span> <span><input name=\"wantDate\" id=\"wantDate\" type=\"checkbox\" value=\"토\">토</span>\r\n");
      out.write("\t\t\t\t\t\t\t<span><input name=\"wantDate\" id=\"wantDate\" type=\"checkbox\" value=\"일\">일</span>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<!-- 원하는  요일 체크박스 출력 함수 -->\r\n");
      out.write("\t\t\t\t\t\t ");

						String day[] = {"월", "화", "수", "목", "금", "토", "일"};
						
						if(dto.getWantDate() != null){
						   for(int i = 0; i < dto.getWantDate().length; i++){
						      System.out.println(dto.getWantDate()[i] + i+"번째 요일");
						      for(int j = 0; j< day.length; j++){
						         if(dto.getWantDate()[i].equals(day[j])){
						            
      out.write("\r\n");
      out.write("\t\t\t\t\t\t            <script>\r\n");
      out.write("\t\t\t\t\t\t            $(document).ready(function () {\r\n");
      out.write("\t\t\t\t\t\t               \r\n");
      out.write("\t\t\t\t\t\t               $(\"input[value=");
      out.print(dto.getWantDate()[i]);
      out.write("]\").prop(\"checked\", true);\r\n");
      out.write("\t\t\t\t\t\t            });\r\n");
      out.write("\t\t\t\t\t\t            </script>\r\n");
      out.write("\t\t\t\t\t\t            ");

						         }
						      }
						   }
						}
						
      out.write(" \r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<tr style=\" height: 35px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<td>원하는 지역 : </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t <select name=\"wantLocal\" id=\"wantLocal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"서울\">서울</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"경기도\">경기도</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"강원도\">강원도</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"충청남도\">충청남도</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"충청북도\">충청북도</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"전라북도\">전라북도</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"전라남도\">전라남도</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"경상북도\">경상북도</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"경상남도\">경상남도</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t    </td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<tr style=\" height: 35px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<td>원하는 시간대 : </td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("                            <select name=\"wantTime\" id=\"wantTime\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"6시~10시\">6시~10시</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"10시~12시\">10시~12시</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"12시~16시\">12시~16시</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"16시~20시\">16시~20시</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"20시~24시\">20시~24시</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t    </td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t<!-- 경력 커리어 셀렉 출력 함수 -->\r\n");
      out.write("\t\t\t<!-- 지역 select문 옵션 출력 함수 -->\t\t\r\n");
      out.write("\t\t\t<!-- 시간대 select문 옵션 출력 함수 -->\r\n");
      out.write("\t\t\t\t\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\t\t\t\t$(document).ready(function () {\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#career\").val('");
      out.print(dto.getCareer() );
      out.write("');\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#wantLocal\").val('");
      out.print(dto.getWantLocal() );
      out.write("');\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#wantTime\").val('");
      out.print(dto.getWantTime() );
      out.write("');\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               </div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("<!-- \t=================================    box2 끝   =================================   -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"boxs box3\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"image_file\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
	if (dto.getRealFileName() == null || dto.getRealFileName() == "null") {
					
      out.write("\r\n");
      out.write("\t\t\t\t<span>\t<img src='./image/mainImage.png'\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border-radius: 100%;\" width='110x' height='110px'> </span>\r\n");
      out.write("\t\t\t\t\t");

						} else {
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<span>\t<img src='http://localhost:8097/ProjectBaby/upload/");
      out.print(dto.getRealFileName());
      out.write("'\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border-radius: 100%;\" width='110px' height='110px'> </span>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</div> <!-- <div class=\"image_file\" align=\"center\"> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div class=\"form-want-introduce\">\r\n");
      out.write("\t\t\t\t\t<p style=\"text-align: left; padding-left:20px;\">내 계좌번호</p>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"account\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width: 200px; height: 30px;\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(dto.getBankAccount());
      out.write("\"> <br>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<p style=\"text-align: left; padding-left:20px;\">소개글</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("\t             \t");
	if (dto.getIntroduce() == null || dto.getIntroduce() == "null") {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<textarea rows=\"10\" cols=\"25\" name=\"introduce\" placeholder=\"작성된 소개글이 없습니다.\"></textarea>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");

						} else {
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<textarea rows=\"10\" cols=\"25\" name=\"introduce\">");
      out.print(dto.getIntroduce());
      out.write("</textarea>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"finalBtn\" style=\"padding-left: 100px;\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"수정하기\" style=\"width: 100px;\" id=\"finalUpdateBtn\" onclick=\"finalUpdateBtnClick()\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div> <!-- <div class=\"form-want-introduce\"> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div> <!-- <div class=\"boxs box3\"> -->\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<!-- ============================================================================================================================= -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//주소 받아오기\r\n");
      out.write("\r\n");
      out.write("//본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.\r\n");
      out.write("function sample4_execDaumPostcode() {\r\n");
      out.write("\tnew daum.Postcode(\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\toncomplete : function(data) {\r\n");
      out.write("\t\t\t\t\t// 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// 도로명 주소의 노출 규칙에 따라 주소를 표시한다.\r\n");
      out.write("\t\t\t\t\t// 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("\t\t\t\t\tvar roadAddr = data.roadAddress; // 도로명 주소 변수\r\n");
      out.write("\t\t\t\t\tvar extraRoadAddr = ''; // 참고 항목 변수\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("\t\t\t\t\t// 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("\t\t\t\t\tif (data.bname !== ''\r\n");
      out.write("\t\t\t\t\t\t\t&& /[동|로|가]$/g.test(data.bname)) {\r\n");
      out.write("\t\t\t\t\t\textraRoadAddr += data.bname;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t// 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("\t\t\t\t\tif (data.buildingName !== ''\r\n");
      out.write("\t\t\t\t\t\t\t&& data.apartment === 'Y') {\r\n");
      out.write("\t\t\t\t\t\textraRoadAddr += (extraRoadAddr !== '' ? ', '\r\n");
      out.write("\t\t\t\t\t\t\t\t+ data.buildingName : data.buildingName);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t// 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("\t\t\t\t\tif (extraRoadAddr !== '') {\r\n");
      out.write("\t\t\t\t\t\textraRoadAddr = ' (' + extraRoadAddr + ')';\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("\t\t\t\t\tdocument.getElementById('sample4_postcode').value = data.zonecode;\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"sample4_roadAddress\").value = roadAddr;\r\n");
      out.write("\t\t\t\t\t//document.getElementById(\"sample4_jibunAddress\").value = data.jibunAddress;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// 참고항목 문자열이 있을 경우 해당 필드에 넣는다.\r\n");
      out.write("\t\t\t\t\t/* if (roadAddr !== '') {\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"sample4_extraAddress\").value = extraRoadAddr;\r\n");
      out.write("\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\tdocument.getElementById(\"sample4_extraAddress\").value = '';\r\n");
      out.write("\t\t\t\t\t} */\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\tvar guideTextBox = document.getElementById(\"guide\");\r\n");
      out.write("\t\t\t\t\tdocument.getElementById(\"sample4_detailAddress\")\r\n");
      out.write("\t\t\t\t\t\t\t.focus();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t}).open();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function finalUpdateBtnClick(){\r\n");
      out.write("\t\r\n");
      out.write("\tvar pwd= $(\"#password\").val();\r\n");
      out.write("\tvar userpwd = '");
      out.print(dao.getPassword(dto.getId()) );
      out.write("'; \r\n");
      out.write("\t\r\n");
      out.write("\t/* 자바스크립트에서 자바값 호출시  ''를 써줍시다. */\r\n");
      out.write("\t\r\n");
      out.write("\t if(pwd == \"\"){\r\n");
      out.write("\t\t alert(\"패스워드를 입력해주세요\");\r\n");
      out.write("\t } else if(pwd != userpwd){\r\n");
      out.write("\t\t alert(\"패스워드가 일치하지 않습니다\")\r\n");
      out.write("\t }else if(pwd == userpwd){\r\n");
      out.write("\t\t alert(\"정상적으로 프로필이 수정되었습니다.\")\r\n");
      out.write("\t } \r\n");
      out.write("\t \r\n");
      out.write("\t \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--// container -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"footerWrap\">\r\n");
      out.write("\t\t<div class=\"footer clearfix\">\r\n");
      out.write("\t\t\t<!-- <img src=\"images/front/\" alt=\"\" class=\"footer__logo\"> -->\r\n");
      out.write("\t\t\t<!-- <p>오마이베이비</p> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<address class=\"footer__info\">\r\n");
      out.write("\t\t\t\t<p class=\"mb10\"></p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"footer__menu\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"inner_list clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>대표이사: </li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>사업자 등록번호: </li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>주소:서울특별시 </li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"inner_list clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#n\">통신판매업신고 : </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#n\" class=\"btn_policy\">이용약관</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#n\" class=\"btn_personal\">개인정보취급방침</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>E-mail : </li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"inner_list clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>TEL : </li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>FAX : </li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>COPYRIGHT Corporation. ALL RIGHTS RESERVED.</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</address>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<!-- // footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 로그인 팝업창 -->\r\n");
      out.write("\t<div class=\"lp_bg\"></div>\r\n");
      out.write("\t<div class=\"lp_box lp_box_s lp_login\">\r\n");
      out.write("\t\t<h3 class=\"lp_sbj font_square\"><a href=\"index.html\">\r\n");
      out.write("\t\t\t\t<p>로그인</p>\r\n");
      out.write("\t\t\t</a></h3>\r\n");
      out.write("\t\t<a href=\"#n\" class=\"btn_close_lp\"><img src=\"images/front/ico_close_lp_s.png\" alt=\"닫기\"></a>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"lp_cn tc\">\r\n");
      out.write("\t\t\t<input type=\"email\" class=\"user_email mb5\" placeholder=\"이메일\" style=\"width: 100%;\">\r\n");
      out.write("\t\t\t<input type=\"password\" class=\"user_pw\" placeholder=\"비밀번호\" style=\"width: 100%;\">\r\n");
      out.write("\t\t\t<p class=\"login_setting mb10 clearfix tl\">\r\n");
      out.write("\t\t\t\t<span class=\"pr10\"><input type=\"checkbox\"><label>ID 저장</label></span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"#n\" class=\"btn_gray_s fr pw_reset_info\">비밀번호 설정</a>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<a href=\"#n\" class=\"btn_blue_l btn_lp_login2\">로그인</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
