/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-04-24 08:21:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import main.BabyMemberDao;
import main.BabyMemberDto;
import main.BabyMemberDto;

public final class mypage_005fimageUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/./include/footer.jsp", Long.valueOf(1587715415236L));
    _jspx_dependants.put("/./include/header.jsp", Long.valueOf(1587715415244L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("main.BabyMemberDao");
    _jspx_imports_classes.add("main.BabyMemberDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Oh My Baby</title>\r\n");
      out.write("\r\n");
      out.write("<!-- favicon 16, 24, 32, 64, 152 -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"./images/front/favicon.ico\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" href=\"./images/front/icon_57.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"72x72\"\r\n");
      out.write("\thref=\"./images/front/icon_72.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"114x114\"\r\n");
      out.write("\thref=\"./images/front/icon_114.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"144x144\"\r\n");
      out.write("\thref=\"./images/front/icon_144.png\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"./css/front/reset.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/front/common.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/front/layout.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/front/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/front/jquery-3.1.0.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"js/front/jquery.bxslider.js\"></script>\r\n");
      out.write("<script src=\"js/front/common.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\">\r\n");
      out.write("<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 자바스크립트 -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");

	BabyMemberDto babyMemberDto = (BabyMemberDto) session.getAttribute("login");
	if (babyMemberDto != null) {
		System.out.println("로그인후 dto" + babyMemberDto.toString());
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<header class=\"headerWrap\">\r\n");
      out.write("\t\t<div class=\"header clearfix tr\">\r\n");
      out.write("\t\t\t<div class=\"header_topSec clearfix\">\r\n");
      out.write("\t\t\t\t");

					if (babyMemberDto != null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t");

					if (babyMemberDto.getAuth() == 1) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t<li>");
      out.print(babyMemberDto.getName());
      out.write("님 환영합니다</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"admin?type=moveAdmin\" id=\"loginBtn\">관리자페이지</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"login?type=logout\" id=\"loginBtn\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t<li>");
      out.print(babyMemberDto.getName());
      out.write("님 환영합니다</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"mypage_point.jsp\" id=\"loginBtn\">마이페이지</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"login?type=logout\" id=\"loginBtn\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"login?type=moveLogin\" id=\"loginBtn\">로그인</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"register?type=moveRegister\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"inner_header clearfix\">\r\n");
      out.write("\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t<a href=\"main.jsp\" class=\"logo\"> <img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"images/front/logo.png\"> <!-- <span>내 아이를 부탁해</span> -->\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t");

					if (babyMemberDto != null) {
						if (babyMemberDto.getAuth() == 1) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"gnb clearfix\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"mypage_point.jsp\">회원정보관리</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li><a href=\"\">회원정보 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\"></a></li> -->\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">Mypage</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_main.jsp\">예약내역 확인</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_imageUpdate.jsp\">프로필 사진 업데이트</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_point.jsp\">내 포인트 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_profile.jsp\">내 계정 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"employee.jsp\">Service</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"employee.jsp\">돌봄 신청</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"searchSitterBoard\">구인구직</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"comHere.jsp\">오시는길</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"qna.jsp\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- <li><a href=\"\">커뮤니티</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">후기게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">자유게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");
	}else {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul class=\"gnb clearfix\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"mypage_point.jsp\">Mypage</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_main.jsp\">예약내역 확인</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"mypage_imageUpdate.jsp\">프로필 사진 업데이트</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_point.jsp\">내 포인트 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_profile.jsp\">내 계정 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"employee.jsp\">Service</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"employee.jsp\">돌봄 신청</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"searchSitterBoard\">구인구직</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"comHere.jsp\">오시는길</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"qna.jsp\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- <li><a href=\"\">커뮤니티</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">후기게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">자유게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					}
					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"gnb clearfix\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"employee.jsp\">Service</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"employee.jsp\">돌봄 신청</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"searchSitterBoard\">구인구직</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"comHere.jsp\">오시는길</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"qna.jsp\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- <li><a href=\"\">커뮤니티</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">후기게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">자유게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					}
					
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!--// header -->");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".abs {\r\n");
      out.write("\tcolor: #ff9999\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypage .boxs {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-direction: row;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\r\n");
      out.write("\t/*     margin-right: 10px; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypage .box1 {\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("\theight: 550px;\r\n");
      out.write("\twidth: 300px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\t/*   align-self:center; */\r\n");
      out.write("\tbackground-color: rgba(205, 255, 254, 0.8);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypage .box2 {\r\n");
      out.write("\tflex-direction: column;\r\n");
      out.write("\theight: 550px;\r\n");
      out.write("\twidth: 800px;\r\n");
      out.write("\tbackground-color: rgba(190, 255, 239, 0.8);\r\n");
      out.write("\tpadding-left: 50px;\r\n");
      out.write("\tpadding-right: 80px;\r\n");
      out.write("\tpadding-bottom: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypage .row1 {\r\n");
      out.write("\theight: 120px;\r\n");
      out.write("\t/* background-color:black; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypage .row2 {\r\n");
      out.write("\tpadding-top: 30px;\r\n");
      out.write("\theight: 275px;\r\n");
      out.write("\t/*  background-color:blue;  */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypage .items {\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tflex-direction: row;\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tpadding-top: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypage .item1 {\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("\theight: 275px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypage .item2 {\r\n");
      out.write("\twidth: 470px;\r\n");
      out.write("\theight: 250px;\r\n");
      out.write("\t/*  background-color:orange;  */\r\n");
      out.write("\tpadding-left: 10px;\r\n");
      out.write("\tpadding-top: 45px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypage .borderTable {\r\n");
      out.write("\tborder: 3px solid #7f8c8d;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypage .keyTr {\r\n");
      out.write("\theight: 40px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypage .keyTd {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypage .row3 {\r\n");
      out.write("\theight: 155px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* vertical-align: middle; */\r\n");
      out.write(".menu>a:hover {\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("\tcolor: #ff9999;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypage .content {\r\n");
      out.write("margin-bottom:100px;\r\n");
      out.write("}  \r\n");
      out.write("</style>\r\n");
      out.write("\r\n");

	BabyMemberDao dao = BabyMemberDao.getInstance();
	BabyMemberDto dto = (BabyMemberDto) request.getSession().getAttribute("login");

	BabyMemberDto sitterDto = dao.getDetail(dto.getSitterId());

	System.out.println(dto.getRealFileName());


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- content 영역 -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"container_inner mypage\">\r\n");
      out.write("\t<!-- 필요 없으면 div 삭제 (필요한거 남기고!) 배결색은 style만 삭제하면 되요~~!! -->\r\n");
      out.write("\t<div class=\"cont1 content clearfix mypage\" style=\"height: 550px\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"boxs box1\">\r\n");
      out.write("\t\t\t<p style=\"padding-top: 30px;\">\r\n");
      out.write("\t\t\t\t<b class=\"abs\" style=\"font-size: 25pt;\">MyPage</b>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t");

						if (dto.getRealFileName() == null || dto.getRealFileName() == "null") {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<span><img src='./image/mainImage.png'\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border-radius: 100%;\" width='110x' height='110px'> </span>\r\n");
      out.write("\t\t\t\t\t");

						} else {
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<span><img\r\n");
      out.write("\t\t\t\t\t\tsrc='http://localhost:8097/ProjectBaby/upload/");
      out.print(dto.getRealFileName());
      out.write("'\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border-radius: 100%;\" width='110x' height='110px'> </span>\r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<table style=\"background-color: #f0f0f0; height: 30px;\">\r\n");
      out.write("\t\t\t\t<col width=\"130px\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"text-align: center; font-size: 15pt;\">\r\n");
      out.write("\t\t\t\t\t\t<p style=\"padding-top: 5px;\">");
      out.print(dto.getName());
      out.write("님\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<p\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"font-size: 9pt; text-align: center; font-weight: bold; padding-bottom: 10px;\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.print(dto.getId());
      out.write("</p>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<table\r\n");
      out.write("\t\t\t\t\tstyle=\"background-color: #f0f0f0; size: '30'; font-size: '14px'; height: '13px'; margin-left: 50px;\">\r\n");
      out.write("\t\t\t\t\t<col width=\"200px\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t<p style=\"margin: 3px; padding-top: 17px;\" class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t <a href=\"mypage_main.jsp\">예약 내역 확인</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t<p style=\"margin: 3px;\" class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t&nbsp;&nbsp;<img src='./image/arrow.png' width='10px' height='10px' /> &nbsp;\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"mypage_imageUpdate.jsp\">프로필 사진 업데이트</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t<p style=\"margin: 3px;\" class=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"mypage_point.jsp\">내 포인트 관리</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <a href=\"bbsWrite?type=write\"> -->\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td style=\"text-align: center\">\r\n");
      out.write("\t\t\t\t\t\t\t<p style=\"margin: 3px; color: #ff9999; padding-bottom: 17px;\"\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"menu\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"mypage_profile.jsp\">내 계정 관리</a>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"boxs box2\">\r\n");
      out.write("\t\t\t<div class=\"row1 rows\">\r\n");
      out.write("\t\t\t\t<!--  내 예약 내역/프로필   -->\r\n");
      out.write("\t\t\t\t<p style=\"padding-top: 50px;\">\r\n");
      out.write("\t\t\t\t\t<b class=\"title\" style=\"font-size: 15pt; color: #82a3d4;\">프로필\r\n");
      out.write("\t\t\t\t\t\t사진 업데이트</b>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<form action=\"userProfileImageServlet\" method=\"post\"\r\n");
      out.write("\t\t\t\tenctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t<div class=\"row2 rows\">\r\n");
      out.write("\t\t\t\t\t<div class=\"items\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item1\" style=\"text-align: center;\">\r\n");
      out.write("\t\t\t\t\t\t\t<p style=\"padding-top: 30px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
	if (dto.getRealFileName() == null || dto.getRealFileName() == "null") {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<img src='./image/mainImage.png'\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border-radius: 100%;\" width='150px' height='150px'> \r\n");
      out.write("\t\t\t\t\t");

						} else {
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<img src='http://localhost:8097/ProjectBaby/upload/");
      out.print(dto.getRealFileName());
      out.write("'\r\n");
      out.write("\t\t\t\t\t\tstyle=\"border-radius: 100%;\" width='150px' height='150px'> \r\n");
      out.write("\t\t\t\t\t");

						}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<p style=\"padding-bottom: 17px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<b style=\"font-size: 15pt;\">");
      out.print(dto.getName());
      out.write("</b>\r\n");
      out.write("\t\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"item2\">\r\n");
      out.write("\t\t\t\t\t\t\t<table class=\"item2_table\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- style=\"border: 2px  solid  #CDFFFE ;\" -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"120px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<col width=\"350px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr class=\"keyTr borderTable\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"keyTd borderTable\" style=\"text-align: center;\"><b\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"font-size: 18px;\"> id </b></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"keyTd borderTable\"><b style=\"font-size: 16px;\">");
      out.print(dto.getId());
      out.write("</b>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr class=\"keyTr borderTable\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"keyTd borderTable\" rowspan='2'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"text-align: center;\"><b\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tstyle=\"font-size: 16px; align: center\"> 사진업로드 </b></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"keyTd borderTable\" ><input type=\"file\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tname=\"imageFile\"> <input type=\"hidden\" name=\"loginId\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(dto.getId());
      out.write("\"></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<tr class=\"keyTr borderTable\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<td class=\"keyTd borderTable\"><b style=\"font-size: 16px;\">※\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t이미지 파일만을 선택해 업데이트하세요</b></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<p style=\"text-align: right; padding-top:30px;\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"등록\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 120px; font-size: 20px; height: 40px;\">\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"row3 rows\">\r\n");
      out.write("<!-- \t\t\t\t\t<p style=\"text-align: right;\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" value=\"등록\"\r\n");
      out.write("\t\t\t\t\t\t\tstyle=\"width: 120px; font-size: 20px; height: 40px;\">\r\n");
      out.write("\t\t\t\t\t</p>\r\n");
      out.write(" -->\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!--// container -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"footerWrap\">\r\n");
      out.write("\t\t<div class=\"footer clearfix\">\r\n");
      out.write("\t\t\t<!-- <img src=\"images/front/\" alt=\"\" class=\"footer__logo\"> -->\r\n");
      out.write("\t\t\t<!-- <p>오마이베이비</p> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<address class=\"footer__info\">\r\n");
      out.write("\t\t\t\t<p class=\"mb10\"></p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"footer__menu\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"inner_list clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>대표이사: </li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>사업자 등록번호: </li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>주소:서울특별시 </li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"inner_list clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#n\">통신판매업신고 : </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#n\" class=\"btn_policy\">이용약관</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#n\" class=\"btn_personal\">개인정보취급방침</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>E-mail : </li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"inner_list clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>TEL : </li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>FAX : </li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>COPYRIGHT Corporation. ALL RIGHTS RESERVED.</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</address>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<!-- // footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 로그인 팝업창 -->\r\n");
      out.write("\t<div class=\"lp_bg\"></div>\r\n");
      out.write("\t<div class=\"lp_box lp_box_s lp_login\">\r\n");
      out.write("\t\t<h3 class=\"lp_sbj font_square\"><a href=\"index.html\">\r\n");
      out.write("\t\t\t\t<p>로그인</p>\r\n");
      out.write("\t\t\t</a></h3>\r\n");
      out.write("\t\t<a href=\"#n\" class=\"btn_close_lp\"><img src=\"images/front/ico_close_lp_s.png\" alt=\"닫기\"></a>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"lp_cn tc\">\r\n");
      out.write("\t\t\t<input type=\"email\" class=\"user_email mb5\" placeholder=\"이메일\" style=\"width: 100%;\">\r\n");
      out.write("\t\t\t<input type=\"password\" class=\"user_pw\" placeholder=\"비밀번호\" style=\"width: 100%;\">\r\n");
      out.write("\t\t\t<p class=\"login_setting mb10 clearfix tl\">\r\n");
      out.write("\t\t\t\t<span class=\"pr10\"><input type=\"checkbox\"><label>ID 저장</label></span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"#n\" class=\"btn_gray_s fr pw_reset_info\">비밀번호 설정</a>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<a href=\"#n\" class=\"btn_blue_l btn_lp_login2\">로그인</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
