/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-04-24 08:16:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import main.BabyMemberDto;

public final class registerSitter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/./include/footer.jsp", Long.valueOf(1587715415236L));
    _jspx_dependants.put("/./include/header.jsp", Long.valueOf(1587715415244L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("main.BabyMemberDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tbox-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-container {\r\n");
      out.write("\tmargin-left: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-container>* {\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".blackLabel {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\twidth: 80px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-check {\r\n");
      out.write("\tmargin-top: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-address>* {\r\n");
      out.write("\tmargin-bottom: 10px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Oh My Baby</title>\r\n");
      out.write("\r\n");
      out.write("<!-- favicon 16, 24, 32, 64, 152 -->\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"./images/front/favicon.ico\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" href=\"./images/front/icon_57.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"72x72\"\r\n");
      out.write("\thref=\"./images/front/icon_72.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"114x114\"\r\n");
      out.write("\thref=\"./images/front/icon_114.png\">\r\n");
      out.write("<link rel=\"apple-touch-icon\" sizes=\"144x144\"\r\n");
      out.write("\thref=\"./images/front/icon_144.png\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"./css/front/reset.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/front/common.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/front/layout.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"./css/front/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"js/front/jquery-3.1.0.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"js/front/jquery.bxslider.js\"></script>\r\n");
      out.write("<script src=\"js/front/common.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\">\r\n");
      out.write("<!-- 부가적인 테마 -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 합쳐지고 최소화된 최신 자바스크립트 -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");

	BabyMemberDto babyMemberDto = (BabyMemberDto) session.getAttribute("login");
	if (babyMemberDto != null) {
		System.out.println("로그인후 dto" + babyMemberDto.toString());
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\t<header class=\"headerWrap\">\r\n");
      out.write("\t\t<div class=\"header clearfix tr\">\r\n");
      out.write("\t\t\t<div class=\"header_topSec clearfix\">\r\n");
      out.write("\t\t\t\t");

					if (babyMemberDto != null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t");

					if (babyMemberDto.getAuth() == 1) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t<li>");
      out.print(babyMemberDto.getName());
      out.write("님 환영합니다</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"admin?type=moveAdmin\" id=\"loginBtn\">관리자페이지</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"login?type=logout\" id=\"loginBtn\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t<li>");
      out.print(babyMemberDto.getName());
      out.write("님 환영합니다</li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"mypage_point.jsp\" id=\"loginBtn\">마이페이지</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"login?type=logout\" id=\"loginBtn\">로그아웃</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"clearfix\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"login?type=moveLogin\" id=\"loginBtn\">로그인</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"register?type=moveRegister\">회원가입</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"inner_header clearfix\">\r\n");
      out.write("\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t<a href=\"main.jsp\" class=\"logo\"> <img\r\n");
      out.write("\t\t\t\t\t\tsrc=\"images/front/logo.png\"> <!-- <span>내 아이를 부탁해</span> -->\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t");

					if (babyMemberDto != null) {
						if (babyMemberDto.getAuth() == 1) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"gnb clearfix\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"mypage_point.jsp\">회원정보관리</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li><a href=\"\">회원정보 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\"></a></li> -->\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t\t<li><a href=\"\">Mypage</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_main.jsp\">예약내역 확인</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_imageUpdate.jsp\">프로필 사진 업데이트</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_point.jsp\">내 포인트 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_profile.jsp\">내 계정 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"employee.jsp\">Service</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"employee.jsp\">돌봄 신청</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"searchSitterBoard\">구인구직</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"comHere.jsp\">오시는길</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"qna.jsp\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- <li><a href=\"\">커뮤니티</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">후기게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">자유게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");
	}else {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<ul class=\"gnb clearfix\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"mypage_point.jsp\">Mypage</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_main.jsp\">예약내역 확인</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"mypage_imageUpdate.jsp\">프로필 사진 업데이트</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_point.jsp\">내 포인트 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"mypage_profile.jsp\">내 계정 관리</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"employee.jsp\">Service</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"employee.jsp\">돌봄 신청</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"searchSitterBoard\">구인구직</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"comHere.jsp\">오시는길</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"qna.jsp\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- <li><a href=\"\">커뮤니티</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">후기게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">자유게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					}
					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"gnb clearfix\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"employee.jsp\">Service</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"employee.jsp\">돌봄 신청</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"searchSitterBoard\">구인구직</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li><a href=\"\">고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"comHere.jsp\">오시는길</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"qna.jsp\">Q&A</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<!-- <li><a href=\"\">커뮤니티</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"sub_menu\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">후기게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"\">자유게시판</a></li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t");

					}
					
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<!--// header -->");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div align=\"center\">\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- submit시 RegiInfoServlet에 method방식은 pos에\r\n");
      out.write("      type registerAf와 값들을 가지고 이동한다 -->\r\n");
      out.write("\t\t<form id=\"register-form\" action=\"register\" method=\"post\">\r\n");
      out.write("\t\t\t<div class=\"form-container\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"type\" value=\"registerSitterAf\">\r\n");
      out.write("\t\t\t\t<div class=\"form-id\">\r\n");
      out.write("\t\t\t\t\t<span class=\"blackLabel\">id(이메일)</span> <input type=\"text\" id=\"id\"\r\n");
      out.write("\t\t\t\t\t\tname=\"id\" size=\"20\"> <span id=\"idcheck\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"font-size: 8px\"> <input type=\"button\" id=\"btn\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"id확인\"> <span class=\"id-check-text\">id 확인시\r\n");
      out.write("\t\t\t\t\t\t\t텍스트</span>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t<!-- 아이디 확인시 클릭시 이메일인증 번호를 전송 -->\r\n");
      out.write("\t\t\t\t\t<div class=\"form-check\" style=\"display: none;\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"check-email-input\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"인증번호를 입력하세요\">&nbsp;&nbsp;<input\r\n");
      out.write("\t\t\t\t\t\t\ttype=\"button\" class=\"check-email-button\" value=\"인증번호 확인\">\r\n");
      out.write("\t\t\t\t\t\t<span class=\"check-email-text\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-password\">\r\n");
      out.write("\t\t\t\t\t<span class=\"blackLabel\">패스워드</span><input type=\"password\" name=\"password\"\r\n");
      out.write("\t\t\t\t\t\tsize=\"20\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-name\">\r\n");
      out.write("\t\t\t\t\t<span class=\"blackLabel\">이름</span><input type=\"text\" name=\"name\"\r\n");
      out.write("\t\t\t\t\t\tsize=\"20\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-age\">\r\n");
      out.write("\t\t\t\t\t<span class=\"blackLabel\">나이</span><input type=\"text\" name=\"age\"\r\n");
      out.write("\t\t\t\t\t\tsize=\"20\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-gender\">\r\n");
      out.write("\t\t\t\t\t<span class=\"blackLabel\">성별</span> <input type=\"radio\" name=\"gender\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"남\"> <span>남</span> <input type=\"radio\"\r\n");
      out.write("\t\t\t\t\t\tname=\"gender\" value=\"여\"><span>여</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-phone-number\">\r\n");
      out.write("\t\t\t\t\t<span class=\"blackLabel\">휴대폰 번호</span> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tname=\"numberFirst\" style=\"width: 70px\">&nbsp;-&nbsp;<input\r\n");
      out.write("\t\t\t\t\t\ttype=\"text\" name=\"numberSecond\" style=\"width: 70px\">&nbsp;-&nbsp;<input\r\n");
      out.write("\t\t\t\t\t\ttype=\"text\" name=\"numberThird\" style=\"width: 70px\">\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-address\">\r\n");
      out.write("\t\t\t\t\t<div>주소</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"zipCode\" id=\"sample4_postcode\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"우편번호\"> <input type=\"button\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"sample4_execDaumPostcode()\" value=\"우편번호 찾기\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div></div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"roadAddress\" id=\"sample4_roadAddress\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"도로명주소\" size=\"30\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<span id=\"guide\" style=\"color: #999; display: none\"></span>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" name=\"detailAddress\" id=\"sample4_detailAddress\"\r\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"상세주소\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-want-pay\">\r\n");
      out.write("\t\t\t\t\t<span  class=\"blackLabel\">원하는 시급 </span> <input type=\"number\" name=\"wantPay\" min=\"8600\" step = 100\r\n");
      out.write("\t\t\t\t\t\tvalue=\"8590\"><span>원</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-career\">\r\n");
      out.write("\t\t\t\t\t<span  class=\"blackLabel\">경력</span> <select name=\"career\">\r\n");
      out.write("\t\t\t\t\t\t<option selected value=\"신입\">신입</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1~3년\">1~3년</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"4~5년\">4~5년</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"5년초과\">5년초과</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div>근무</div>\r\n");
      out.write("\t\t\t\t<div class=\"form-want-day-of-week\">\r\n");
      out.write("\t\t\t\t\t<span class=\"blackLabel\">원하는 요일</span>\r\n");
      out.write("\t\t\t\t\t <span><input type=\"checkbox\" name=\"wantDate\" value=\"월\">월</span>\r\n");
      out.write("\t\t\t\t\t<span><input type=\"checkbox\" name=\"wantDate\" value=\"화\">화</span>\r\n");
      out.write("\t\t\t\t\t<span><input name=\"wantDate\" type=\"checkbox\" value=\"수\">수</span>\r\n");
      out.write("\t\t\t\t\t<span><input name=\"wantDate\" type=\"checkbox\" value=\"목\">목</span>\r\n");
      out.write("\t\t\t\t\t<span> <input name=\"wantDate\" type=\"checkbox\" value=\"금\">금</span> \r\n");
      out.write("\t\t\t\t\t<span><input name=\"wantDate\" type=\"checkbox\" value=\"토\">토</span>\r\n");
      out.write("\t\t\t\t\t<span><input name=\"wantDate\" type=\"checkbox\" value=\"일\">일</span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-want-address\">\r\n");
      out.write("\t\t\t\t\t<span  class=\"blackLabel\">원하는 지역</span>\r\n");
      out.write("\t\t\t\t\t <select name=\"wantLocal\">\r\n");
      out.write("\t\t\t\t\t\t<option selected value=\"서울\">서울</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"경기도\">경기도</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"강원도\">강원도</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"충청남도\">충청남도</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"충청북도\">충청북도</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"전라북도\">전라북도</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"전라남도\">전라남도</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"경상북도\">경상북도</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"경상남도\">경상남도</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-want-time\">\r\n");
      out.write("\t\t\t\t\t<span>원하는 시간대</span> \r\n");
      out.write("\t\t\t\t\t<select name=\"wantTime\">\r\n");
      out.write("\t\t\t\t\t\t<option selected value=\"6시~10시\">6시 ~ 10시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"10시~12시\">10시 ~ 12시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"12시~16시\">12시 ~ 16시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"16시~20시\">16시 ~ 20시</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"20시~24시\">20시 ~ 24시</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-want-introduce\">\r\n");
      out.write("\t\t\t\t\t<div>자기소개</div>\r\n");
      out.write("\t\t\t\t\t<textarea rows=\"15\" cols=\"30\" name=\"introduce\"></textarea>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"form-submit\">\r\n");
      out.write("\t\t\t\t\t<!-- <input type=\"submit\" value=\"회원가입\" id=\"submitBtn\"> -->\r\n");
      out.write("\t\t\t\t\t<button type=\"button\" class=\"btn btn-primary\" id=\"submitBtn\">회원가입</button>\r\n");
      out.write("\t\t\t\t\t<span class=\"submit-text\"></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<footer class=\"footerWrap\">\r\n");
      out.write("\t\t<div class=\"footer clearfix\">\r\n");
      out.write("\t\t\t<!-- <img src=\"images/front/\" alt=\"\" class=\"footer__logo\"> -->\r\n");
      out.write("\t\t\t<!-- <p>오마이베이비</p> -->\r\n");
      out.write("\r\n");
      out.write("\t\t\t<address class=\"footer__info\">\r\n");
      out.write("\t\t\t\t<p class=\"mb10\"></p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<ul class=\"footer__menu\">\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"inner_list clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>대표이사: </li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>사업자 등록번호: </li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>주소:서울특별시 </li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"inner_list clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#n\">통신판매업신고 : </a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#n\" class=\"btn_policy\">이용약관</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"#n\" class=\"btn_personal\">개인정보취급방침</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>E-mail : </li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"inner_list clearfix\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>TEL : </li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>FAX : </li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>COPYRIGHT Corporation. ALL RIGHTS RESERVED.</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</address>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</footer>\r\n");
      out.write("\t<!-- // footer -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!-- 로그인 팝업창 -->\r\n");
      out.write("\t<div class=\"lp_bg\"></div>\r\n");
      out.write("\t<div class=\"lp_box lp_box_s lp_login\">\r\n");
      out.write("\t\t<h3 class=\"lp_sbj font_square\"><a href=\"index.html\">\r\n");
      out.write("\t\t\t\t<p>로그인</p>\r\n");
      out.write("\t\t\t</a></h3>\r\n");
      out.write("\t\t<a href=\"#n\" class=\"btn_close_lp\"><img src=\"images/front/ico_close_lp_s.png\" alt=\"닫기\"></a>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"lp_cn tc\">\r\n");
      out.write("\t\t\t<input type=\"email\" class=\"user_email mb5\" placeholder=\"이메일\" style=\"width: 100%;\">\r\n");
      out.write("\t\t\t<input type=\"password\" class=\"user_pw\" placeholder=\"비밀번호\" style=\"width: 100%;\">\r\n");
      out.write("\t\t\t<p class=\"login_setting mb10 clearfix tl\">\r\n");
      out.write("\t\t\t\t<span class=\"pr10\"><input type=\"checkbox\"><label>ID 저장</label></span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"#n\" class=\"btn_gray_s fr pw_reset_info\">비밀번호 설정</a>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<a href=\"#n\" class=\"btn_blue_l btn_lp_login2\">로그인</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tlet emailAuthData = \"\";\r\n");
      out.write("\r\n");
      out.write("\t\t//주소 받아오기\r\n");
      out.write("\r\n");
      out.write("\t\t//본 예제에서는 도로명 주소 표기 방식에 대한 법령에 따라, 내려오는 데이터를 조합하여 올바른 주소를 구성하는 방법을 설명합니다.\r\n");
      out.write("\t\tfunction sample4_execDaumPostcode() {\r\n");
      out.write("\t\t\tnew daum.Postcode(\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\toncomplete : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t// 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t// 도로명 주소의 노출 규칙에 따라 주소를 표시한다.\r\n");
      out.write("\t\t\t\t\t\t\t// 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.\r\n");
      out.write("\t\t\t\t\t\t\tvar roadAddr = data.roadAddress; // 도로명 주소 변수\r\n");
      out.write("\t\t\t\t\t\t\tvar extraRoadAddr = ''; // 참고 항목 변수\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t// 법정동명이 있을 경우 추가한다. (법정리는 제외)\r\n");
      out.write("\t\t\t\t\t\t\t// 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다.\r\n");
      out.write("\t\t\t\t\t\t\tif (data.bname !== ''\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&& /[동|로|가]$/g.test(data.bname)) {\r\n");
      out.write("\t\t\t\t\t\t\t\textraRoadAddr += data.bname;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t// 건물명이 있고, 공동주택일 경우 추가한다.\r\n");
      out.write("\t\t\t\t\t\t\tif (data.buildingName !== ''\r\n");
      out.write("\t\t\t\t\t\t\t\t\t&& data.apartment === 'Y') {\r\n");
      out.write("\t\t\t\t\t\t\t\textraRoadAddr += (extraRoadAddr !== '' ? ', '\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ data.buildingName : data.buildingName);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t// 표시할 참고항목이 있을 경우, 괄호까지 추가한 최종 문자열을 만든다.\r\n");
      out.write("\t\t\t\t\t\t\tif (extraRoadAddr !== '') {\r\n");
      out.write("\t\t\t\t\t\t\t\textraRoadAddr = ' (' + extraRoadAddr + ')';\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t// 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById('sample4_postcode').value = data.zonecode;\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"sample4_roadAddress\").value = roadAddr;\r\n");
      out.write("\t\t\t\t\t\t\t//document.getElementById(\"sample4_jibunAddress\").value = data.jibunAddress;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t// 참고항목 문자열이 있을 경우 해당 필드에 넣는다.\r\n");
      out.write("\t\t\t\t\t\t\t/* if (roadAddr !== '') {\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"sample4_extraAddress\").value = extraRoadAddr;\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\tdocument.getElementById(\"sample4_extraAddress\").value = '';\r\n");
      out.write("\t\t\t\t\t\t\t} */\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tvar guideTextBox = document.getElementById(\"guide\");\r\n");
      out.write("\t\t\t\t\t\t\tdocument.getElementById(\"sample4_detailAddress\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.focus();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t}).open();\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t//idCheck를 RegiInfoServlet에 넘겨주고 success로 값을 받아온다\r\n");
      out.write("\t\t//값을 정확히 받아오면 console.log에 true or false가 찍힌다\r\n");
      out.write("\t\t$(\"#submitBtn\").prop(\"disabled\", true);\r\n");
      out.write("\t\t$(\"#btn\")\r\n");
      out.write("\t\t\t\t.click(\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\t//alert(\"됨\");   \r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t//이메일 정규식 사용하기\r\n");
      out.write("\t\t\t\t\t\t\tvar regExp = /^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*.[a-zA-Z]{2,3}$/i;\r\n");
      out.write("\t\t\t\t\t\t\tif ($(\"#id\").val().match(regExp) === null) {\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".id-check-text\").css(\"color\", \"#ff0000\");\r\n");
      out.write("\t\t\t\t\t\t\t\t$(\".id-check-text\").html(\"올바른 이메일 형식을 사용해주세요\");\r\n");
      out.write("\t\t\t\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t$\r\n");
      out.write("\t\t\t\t\t\t\t\t\t.ajax({\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\turl : \"./register\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//data : \"id=\" + $(\"#id\").val(),\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t//json타입\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\"type\" : \"idCheck\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\"id\" : $(\"#id\").val()\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tif (data.trim() === \"false\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t//alert(\"사용 가능한 아이디입니다\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$(\".id-check-text\").css(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\", \"#0000ff\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$(\".id-check-text\")\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t.html(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"사용할 수 있는 id입니다. 해당 이메일로 인증번호를 발송하였습니다\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$(\"#submitBtn\").prop(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"disabled\", false);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$(\".check-email\").prop(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"disabled\", \"false\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$(\".form-check\").toggle();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t//email과 연동하는 Ajax 호출 (하단에 선언)#/\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\temailAjax();\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t} else if (data.trim() == \"true\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$(\".id-check-text\").css(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"color\", \"#ff0000\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$(\".id-check-text\").html(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"사용중인 id입니다\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$(\"#id\").val(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t$(\"#submitBtn\").prop(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\"disabled\", true);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\tfunction emailAjax() {\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\turl : \"./email\",\r\n");
      out.write("\t\t\t\ttype : \"get\",\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\"id\" : $(\"#id\").val()\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess : function(emailData) {\r\n");
      out.write("\t\t\t\t\tconsole.log(emailData);\r\n");
      out.write("\t\t\t\t\t//상단에 선언해준 emailAuthData에 data1 할당\r\n");
      out.write("\t\t\t\t\temailAuthData = emailData.trim();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t$(\".check-email-button\").click(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tconsole.log(typeof emailAuthData);\r\n");
      out.write("\t\t\tconsole.log(typeof $(\".check-email-input\").val());\r\n");
      out.write("\t\t\tlet emailInputData = $(\".check-email-input\").val().trim();\r\n");
      out.write("\r\n");
      out.write("\t\t\tif (emailInputData === emailAuthData) {\r\n");
      out.write("\t\t\t\t$(\".check-email-text\").css(\"color\", \"blue\");\r\n");
      out.write("\t\t\t\t$(\".check-email-text\").html(\"인증번호가 확인되었습니다.\");\r\n");
      out.write("\t\t\t\t$(\".check-email-button\").prop(\"disabled\", \"true\");\r\n");
      out.write("\t\t\t\t$(\"#btn\").prop(\"disabled\", \"true\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\t$(\".check-email-text\").css(\"color\", \"red\");\r\n");
      out.write("\t\t\t\tconsole.log(emailAuthData);\r\n");
      out.write("\t\t\t\tconsole.log(\"val = \" + $(\".check-email-input\").val());\r\n");
      out.write("\t\t\t\t$(\".check-email-text\").html(\"인증번호가 올바르지 않습니다. 다시 확인하세요\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t/* if($(\"input\").val() == \"\"){\r\n");
      out.write("\t\t\t$(\"#submitBtn\").prop(\"disabled\", true);\r\n");
      out.write("\t\t\talert(\"비었지롱\");\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$(\"#submitBtn\").prop(\"disabled\", true);\r\n");
      out.write("\t\t\talert(\"아니지롱\");\r\n");
      out.write("\t\t} */\r\n");
      out.write("\t\t$(\"#submitBtn\").click(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t$(\"#register-form\").submit();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
